In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import cv2

%matplotlib inline

In [2]:
def load_image_and_convert_to_grayscale()->np.ndarray:
    image = cv2.imread('Assignment_MV_1_image.png')
    image_gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    image_gray = image_gray.astype(float)
    return image_gray

def display_image(i:np.ndarray)->None:
    #ii = cv2.cvtColor(i, cv2.COLOR_GRAY2BGR)
    cv2.imshow('gray', i)

In [3]:
i = load_image_and_convert_to_grayscale()
print(i)

[[220. 221. 221. ... 230. 230. 230.]
 [220. 221. 221. ... 228. 229. 229.]
 [221. 221. 222. ... 228. 228. 230.]
 ...
 [185. 182. 179. ... 181. 178. 177.]
 [185. 185. 183. ... 187. 186. 183.]
 [182. 183. 183. ... 187. 188. 185.]]


In [6]:
cv2.imshow("gray", i)